#!/bin/sh
ROOT=`pwd`
MSG_BASE="updateHistoryList";
UPDATE_HISTORY_LOG="$ROOT/json/$MSG_BASE.json"
git log --pretty=format:"%s" -1 HEAD | { 
 MSG=$(cat)
 DATE=`date +'%m/%d'`
 if [ $MSG == $MSG_BASE ] ; then
  exit 0
 elif [ `echo "$MSG" | grep "#"` ] ; then
  exit 0
 else
  sed -i -e "1a\  {\n    \"msg\": \"$MSG\",\n    \"date\": \"$DATE\"\n  }," $UPDATE_HISTORY_LOG
  git add $UPDATE_HISTORY_LOG
  git commit -m "$MSG_BASE"
  echo ""
 fi
}