#!/bin/sh
ROOT=`pwd`
UPDATE_HISTORY_LOG="$ROOT/logs/updateHistoryLog.txt"
MSG=`cat $1`
if [ `echo "&MSG" | grep "updateLog"` ] ; then
 exit 0
fi
 echo "$MSG" > temp_file
 cat $UPDATE_HISTORY_LOG >> temp_file
 mv temp_file $UPDATE_HISTORY_LOG
 git add $UPDATE_HISTORY_LOG
 git commit -m "updateLog"
